type ErrorCode = 'isv.SMS_SIGNATURE_SCENE_ILLEGAL' | 'isv.EXTEND_CODE_ERROR' | 'isv.DOMESTIC_NUMBER_NOT_SUPPORTED' | 'isv.DENY_IP_RANGE' | 'isv.DAY_LIMIT_CONTROL' | 'isv.MONTH_LIMIT_CONTROL' | 'isv.SMS_CONTENT_ILLEGAL' | 'isv.SMS_SIGN_ILLEGAL' | 'isp.RAM_PERMISSION_DENY' | 'isv.OUT_OF_SERVICE' | 'isv.PRODUCT_UN_SUBSCRIPT' | 'isv.PRODUCT_UNSUBSCRIBE' | 'isv.ACCOUNT_NOT_EXISTS' | 'isv.ACCOUNT_ABNORMAL' | 'isv.SMS_TEMPLATE_ILLEGAL' | 'isv.SMS_SIGNATURE_ILLEGAL' | 'isv.INVALID_PARAMETERS' | 'isp.SYSTEM_ERROR' | 'isv.MOBILE_NUMBER_ILLEGAL' | 'isv.MOBILE_COUNT_OVER_LIMIT' | 'isv.TEMPLATE_MISSING_PARAMETERS' | 'isv.BUSINESS_LIMIT_CONTROL' | 'isv.INVALID_JSON_PARAM' | 'isv.BLACK_KEY_CONTROL_LIMIT' | 'isv.PARAM_LENGTH_LIMIT' | 'isv.PARAM_NOT_SUPPORT_URL' | 'isv.AMOUNT_NOT_ENOUGH' | 'isv.TEMPLATE_PARAMS_ILLEGAL' | 'SignatureDoesNotMatch' | 'InvalidTimeStamp.Expired' | 'SignatureNonceUsed' | 'InvalidVersion' | 'InvalidAction.NotFound' | 'isv.SIGN_COUNT_OVER_LIMIT' | 'isv.TEMPLATE_COUNT_OVER_LIMIT' | 'isv.SIGN_NAME_ILLEGAL' | 'isv.SIGN_FILE_LIMIT' | 'isv.SIGN_OVER_LIMIT' | 'isv.TEMPLATE_OVER_LIMIT' | 'SIGNATURE_BLACKLIST' | 'isv.SHORTURL_OVER_LIMIT' | 'isv.NO_AVAILABLE_SHORT_URL' | 'isv.SHORTURL_NAME_ILLEGAL' | 'isv.SOURCEURL_OVER_LIMIT' | 'isv.SHORTURL_TIME_ILLEGAL' | 'isv.PHONENUMBERS_OVER_LIMIT' | 'isv.SHORTURL_STILL_AVAILABLE' | 'isv.ERROR_EMPTY_FILE' | 'isp.GATEWAY_ERROR' | 'isv.ERROR_SIGN_NOT_DELETE' | 'isv.ERROR_SIGN_NOT_MODIFY' | 'isv.ERROR_TEMPLATE_NOT_DELETE' | 'isv.ERROR_TEMPLATE_NOT_MODIFY' | 'isv.SMS_OVER_LIMIT' | 'isv.CUSTOMER_REFUSED' | 'isv.SMS_TEST_SIGN_TEMPLATE_LIMIT' | 'isv.SHORTURL_DOMAIN_EMPTY' | 'template_parameter_count_illegal' | 'isv.SMS_TEST_TEMPLATE_PARAMS_ILLEGAL' | 'isv.SMS_TEST_NUMBER_LIMIT' | 'isv.SMS_SIGN_EMOJI_ILLEGAL' | 'isv.SECURITY_FROZEN_ACCOUNT' | 'IS_CLOSE' | 'PARAMS_ILLEGAL' | 'MOBILE_NOT_ON_SERVICE' | 'MOBILE_SEND_LIMIT' | 'MOBILE_ACCOUNT_ABNORMAL' | 'MOBILE_IN_BLACK' | 'MOBLLE_TERMINAL_ERROR' | 'CONTENT_KEYWORD' | 'INVALID_NUMBER' | 'CONTENT_ERROR' | 'REQUEST_SUCCESS' | 'SP_NOT_BY_INTER_SMS' | 'SP_UNKNOWN_ERROR' | 'USER_REJECT' | 'NO_ROUTE' | 'isv.UNSUPPORTED_CONTENT' | 'isv.SMS_CONTENT_MISMATCH_TEMPLATE_TYPE' | 'isv.ONE_CODE_MULTIPLE_SIGN' | 'isv.CODE_EXCEED_LIMIT' | 'isv.CODE_ERROR';

function getErrorMessageByCode(code: ErrorCode): string {
    const errorMessages: { [key in ErrorCode]: string } = {
        'isv.SMS_SIGNATURE_SCENE_ILLEGAL': '签名和模板类型不一致',
        'isv.EXTEND_CODE_ERROR': '扩展码使用错误，相同的扩展码不可用于多个签名',
        'isv.DOMESTIC_NUMBER_NOT_SUPPORTED': '国际/港澳台消息模板不支持发送境内号码',
        'isv.DENY_IP_RANGE': '原IP地址所在的地区被禁用',
        'isv.DAY_LIMIT_CONTROL': '触发日发送限额',
        'isv.MONTH_LIMIT_CONTROL': '触发月发送限额',
        'isv.SMS_CONTENT_ILLEGAL': '短信内容包含禁止发送内容',
        'isv.SMS_SIGN_ILLEGAL': '签名禁止使用',
        'isp.RAM_PERMISSION_DENY': 'RAM权限不足',
        'isv.OUT_OF_SERVICE': '业务停机',
        'isv.PRODUCT_UN_SUBSCRIPT': '未开通云通信产品的阿里云客户',
        'isv.PRODUCT_UNSUBSCRIBE': '产品未开通',
        'isv.ACCOUNT_NOT_EXISTS': '账户不存在',
        'isv.ACCOUNT_ABNORMAL': '账户异常',
        'isv.SMS_TEMPLATE_ILLEGAL': '请检查模板内容与模板参数是否匹配',
        'isv.SMS_SIGNATURE_ILLEGAL': '该账号下找不到对应签名',
        'isv.INVALID_PARAMETERS': '参数格式不正确',
        'isp.SYSTEM_ERROR': '系统出现错误，请重新调用',
        'isv.MOBILE_NUMBER_ILLEGAL': '手机号码格式错误',
        'isv.MOBILE_COUNT_OVER_LIMIT': '调用接口时参数PhoneNumbers中指定的手机号码数量超出限制。',
        'isv.TEMPLATE_MISSING_PARAMETERS': '模板变量中存在未赋值变量',
        'isv.BUSINESS_LIMIT_CONTROL': '触发云通信流控限制',
        'isv.INVALID_JSON_PARAM': '参数格式错误，请修改为字符串值',
        'isv.BLACK_KEY_CONTROL_LIMIT': '黑名单管控',
        'isv.PARAM_LENGTH_LIMIT': '参数超过长度限制',
        'isv.PARAM_NOT_SUPPORT_URL': '变量不支持传入URL',
        'isv.AMOUNT_NOT_ENOUGH': '账户余额不足',
        'isv.TEMPLATE_PARAMS_ILLEGAL': '传入的变量内容和实际申请模板时变量所选择的属性类型不配',
        'SignatureDoesNotMatch': '客户端生成的签名与服务端不匹配',
        'InvalidTimeStamp.Expired': '时间戳或日期已过期',
        'SignatureNonceUsed': '签名随机数已被使用',
        'InvalidVersion': 'API版本号错误',
        'InvalidAction.NotFound': '未找到指定的API，请检查您的URL和方法',
        'isv.SIGN_COUNT_OVER_LIMIT': '超过单自然日签名申请数量上限',
        'isv.TEMPLATE_COUNT_OVER_LIMIT': '超过单自然日模板申请数量上限',
        'isv.SIGN_NAME_ILLEGAL': '签名名称不符合规范',
        'isv.SIGN_FILE_LIMIT': '签名认证材料附件大小超过限制',
        'isv.SIGN_OVER_LIMIT': '签名字符数量超过限制',
        'isv.TEMPLATE_OVER_LIMIT': '模板字符数量超过限制',
        'SIGNATURE_BLACKLIST': '签名内容涉及违规信息',
        'isv.SHORTURL_OVER_LIMIT': '超过单自然日短链申请数量上限',
        'isv.NO_AVAILABLE_SHORT_URL': '该账号无有效短链',
        'isv.SHORTURL_NAME_ILLEGAL': '短链名不能超过13字符',
        'isv.SOURCEURL_OVER_LIMIT': '原始链接字符数量超过限制',
        'isv.SHORTURL_TIME_ILLEGAL': '短链有效期期限超过限制',
        'isv.PHONENUMBERS_OVER_LIMIT': '上传手机号个数超过上限',
        'isv.SHORTURL_STILL_AVAILABLE': '原始链接生成的短链仍在有效期内',
        'isv.ERROR_EMPTY_FILE': '签名文件为空',
        'isp.GATEWAY_ERROR': '调用发送应用模块失败',
        'isv.ERROR_SIGN_NOT_DELETE': '审核中的签名，暂时无法删除',
        'isv.ERROR_SIGN_NOT_MODIFY': '已通过的签名不支持修改',
        'isv.ERROR_TEMPLATE_NOT_DELETE': '审核中的模板，暂时无法删除',
        'isv.ERROR_TEMPLATE_NOT_MODIFY': '已通过的模板不支持修改',
        'isv.SMS_OVER_LIMIT': '单日最多申请模板或签名100条',
        'isv.CUSTOMER_REFUSED': '用户已退订推广短信',
        'isv.SMS_TEST_SIGN_TEMPLATE_LIMIT': '测试模板和签名限制',
        'isv.SHORTURL_DOMAIN_EMPTY': '短链创建失败',
        'template_parameter_count_illegal': '验证码模板仅支持一个验证码作为变量',
        'isv.SMS_TEST_TEMPLATE_PARAMS_ILLEGAL': '测试专用模板中的变量仅支持4~6位纯数字',
        'isv.SMS_TEST_NUMBER_LIMIT': '只能向已绑定的手机号发送',
        'isv.SMS_SIGN_EMOJI_ILLEGAL': '签名不能包含emoji表情',
        'isv.SECURITY_FROZEN_ACCOUNT': '因该账号长时间未使用，出于对您的账号安全考虑，已限制您账号的短信发送',
        'IS_CLOSE': '短信下发时通道被关停',
        'PARAMS_ILLEGAL': '参数错误',
        'MOBILE_NOT_ON_SERVICE': '停机、空号、暂停服务、关机、不在服务区',
        'MOBILE_SEND_LIMIT': '单个号码日、月发送上限，流控超限，频繁发送超限',
        'MOBILE_ACCOUNT_ABNORMAL': '用户账户异常、携号转网、欠费等',
        'MOBILE_IN_BLACK': '手机号在黑名单',
        'MOBLLE_TERMINAL_ERROR': '手机终端问题、内存满、SIM卡满、非法设备等',
        'CONTENT_KEYWORD': '内容关键字拦截',
        'INVALID_NUMBER': '号码状态异常',
        'CONTENT_ERROR': '内容无退订',
        'REQUEST_SUCCESS': '请求成功（平台接到请求，但未接收到运营商侧的回执状态）',
        'SP_NOT_BY_INTER_SMS': '未开通国际短信',
        'SP_UNKNOWN_ERROR': '运营商未知错误',
        'USER_REJECT': '接收用户已退订此业务或产品未开通',
        'NO_ROUTE': '当前短信内容无可用通道发送',
        'isv.UNSUPPORTED_CONTENT': '不支持的短信内容',
        'isv.SMS_CONTENT_MISMATCH_TEMPLATE_TYPE': '短信内容和模板属性不匹配',
        'isv.ONE_CODE_MULTIPLE_SIGN': '一码多签',
        'isv.CODE_EXCEED_LIMIT': '自拓扩展码个数已超过上限',
        'isv.CODE_ERROR': '传入扩展码不可用',
    };

    return errorMessages[code] || 'Error code not found';
}

export { getErrorMessageByCode, ErrorCode }